language: python
matrix:
  include:
  - os: linux
    python: '3.6'
  - os: linux
    python: '3.7'
  - os: linux
    python: '3.8'
install:
- pip install coverage
- pip install codecov
- pip install -U pytest
- pip install -U pytest-cov
- pip install --upgrade setuptools wheel
script:
  - python setup.py install
  - coverage run -m pytest
