language: python
matrix:
  include:
  - os: linux
    python: '3.6'
install:
- pip install coverage
- pip install codecov
- pip install -U pytest
- pip install -U pytest-cov
- pip install -r requirements.txt
script:
  - pip install .
  - coverage run -m pytest
  - pycodestyle nrao_interview/*  scripts/* --max-line-length=120
after_success:
- codecov
