language: python
matrix:
  include:
  - os: linux
    python: '3.6'
install:
- pip install coverage
- pip install codecov
- pip install -U pytest
- pip install -U pytest-cov
- pip install -r requirements.txt
script:
  - pip install .
  - coverage run -m pytest
after_success:
- codecov
